# Language Identification

- https://cs229.stanford.edu/proj2015/324_report.pdf
- https://sites.google.com/view/vardial2021/home
- http://ttg.uni-saarland.de/resources/DSLCC/
- https://mzampieri.com/publications.html
- https://mzampieri.com/papers/dsl2016.pdf

## Make workspace

In [15]:
# Make directories if they don't exist
!mkdir -p datasets
!mkdir -p datasets/DSLCC-v2.0
!mkdir -p datasets/DSLCC-v2.1

## Imports

In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

2022-05-26 09:57:29.470275: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-26 09:57:29.470345: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


## Download datasets

In [3]:
# DSLCC v2.0
if not os.path.exists('datasets/DSLCC-v2.0/train.txt'):
    !cd datasets/DSLCC-v2.0 && curl -o train.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.0/train-dev/train.txt
if not os.path.exists('datasets/DSLCC-v2.0/devel.txt'):
    !cd datasets/DSLCC-v2.0 && curl -o devel.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.0/train-dev/devel.txt
if not os.path.exists('datasets/DSLCC-v2.0/test.txt'):
    !cd datasets/DSLCC-v2.0 && curl -o test.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.0/test/test.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 61.0M  100 61.0M    0     0  5521k      0  0:00:11  0:00:11 --:--:-- 8183k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6939k  100 6939k    0     0  5363k      0  0:00:01  0:00:01 --:--:-- 5367k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3401k  100 3401k    0     0  3246k      0  0:00:01  0:00:01 --:--:-- 3249k


In [14]:
# DSLCC v2.1
if not os.path.exists('datasets/DSLCC-v2.1/train.txt'):
    !cd datasets/DSLCC-v2.1 && curl -o train.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.1/train.txt
if not os.path.exists('datasets/DSLCC-v2.1/devel.txt'):
    !cd datasets/DSLCC-v2.1 && curl -o devel.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.1/devel.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 67.8M  100 67.8M    0     0  10.1M      0  0:00:06  0:00:06 --:--:-- 10.2M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7709k  100 7709k    0     0  8407k      0 --:--:-- --:--:-- --:--:-- 8397k


## Data

### Languages
 
| Group Name                | Language Name       | Language Code |
| ------------------------- | ------------------- | ------------- |
| South Eastern Slavic      | Bulgarian           | bg            |
|                           | Macedonian          | mk            |
| South Western Slavic      | Bosnian             | bs            |
|                           | Croatian            | hr            |
|                           | Serbian             | sr            |
| West-Slavic               | Czech               | cz            |
|                           | Slovak              | sk            |
| Ibero-Romance (Spanish)   | Peninsular Spanish  | es-ES         |
|                           | Argentinian Spanish | es-AR         |
| Ibero-Romance (Portugese) | Brazilian Portugese | pt-BR         |
|                           | European Portugese  | pt-PT         |
| Austronesian              | Indonesian          | id            |
|                           | Malay               | my            |

<table>
    <tr>
        <th>Group Name</th>
        <th>Language Name</th>
        <th>Language Code</th>
    </tr>
    <tr>
        <td rowspan=2>South Eastern Slavic</td>
        <td>Bulgarian</td>
        <td>bg</td>
    </tr>
    <tr>
        <td>Macedonian</td>
        <td>mk</td>
    </tr>
    <tr>
        <td rowspan=3>South Western Slavic</td>
        <td>Bosnian</td>
        <td>bs</td>
    </tr>
    <tr>
        <td>Croatian</td>
        <td>hr</td>
    </tr>
    <tr>
        <td>Serbian</td>
        <td>sr</td>
    </tr>
    <tr>
        <td rowspan=2>West-Slavic</td>
        <td>Czech</td>
        <td>cz</td>
    </tr>
    <tr>
        <td>Slovak</td>
        <td>sk</td>
    </tr>
    <tr>
        <td rowspan=2>Ibero-Romance (Spanish)</td>
        <td>Peninsular Spanish</td>
        <td>es-ES</td>
    </tr>
    <tr>
        <td>Argentinian Spanish</td>
        <td>es-AR</td>
    </tr>
    <tr>
        <td rowspan=2>Ibero-Romance (Portugese)</td>
        <td>Brazilian Portugese</td>
        <td>pt-BR</td>
    </tr>
    <tr>
        <td>European Portugese</td>
        <td>pt-PT</td>
    </tr>
    <tr>
        <td rowspan=2>Astronesian</td>
        <td>Indonesian</td>
        <td>id</td>
    </tr>
    <tr>
        <td>Malay</td>
        <td>my</td>
    </tr>
</table>

In [2]:
train = pd.read_csv('datasets/DSLCC-v2.0/train.txt', sep='\t', names=['sentence', 'language'])
validation = pd.read_csv('datasets/DSLCC-v2.0/devel.txt', sep='\t', names=['sentence', 'language'])
test = pd.read_csv('datasets/DSLCC-v2.0/test.txt', sep='\t', names=['sentence', 'language'])

In [3]:
print(len(train))
print(len(validation))
print(len(test))

236135
26335
13229


In [4]:
print(train['language'].value_counts())

es-ES    17990
es-AR    17808
sr       17442
pt-PT    17284
id       17195
mk       17154
bg       17151
xx       16920
bs       16858
hr       16792
pt-BR    16483
cz       16454
sk       16224
my       14380
Name: language, dtype: int64


In [77]:
print(train.head())

                                            sentence language
0  Зад думите “просто искам да се махна от Българ...       bg
1  Сега нещата там леко потръгнаха с усилията на ...       bg
2  Хърватският филм "Пътят на дините" на режисьор...       bg
3  Министърът на правосъдието на РС Джерард Селма...       bg
4  В крайна сметка войната между Севера и Юга дов...       bg


## Preprocessing

In [3]:
from tensorflow.keras.utils import to_categorical

In [4]:
X_train = train['sentence']
y_train = train['language']

In [7]:
print(X_train.head())
print(y_train.head())

0    Зад думите “просто искам да се махна от Българ...
1    Сега нещата там леко потръгнаха с усилията на ...
2    Хърватският филм "Пътят на дините" на режисьор...
3    Министърът на правосъдието на РС Джерард Селма...
4    В крайна сметка войната между Севера и Юга дов...
Name: sentence, dtype: object
0    bg
1    bg
2    bg
3    bg
4    bg
Name: language, dtype: object


In [5]:
y_train = pd.get_dummies(y_train).to_numpy()

In [9]:
print(y_train)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


### Character n-grams

In [51]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from nltk.util import ngrams

In [149]:
# https://albertauyeung.github.io/2018/06/03/generating-ngrams.html/
s = train['sentence'][0]
tokens = text_to_word_sequence(s)
output = list(ngrams(tokens, 5))
print(s)
print(output)

Зад думите “просто искам да се махна от България” стои осъзнат избор на двеста хиляди българи, които са загубили вяра във възможностите на нацията ни да създаде общество, в което те се чувстват у дома си.
[('зад', 'думите', '“просто', 'искам', 'да'), ('думите', '“просто', 'искам', 'да', 'се'), ('“просто', 'искам', 'да', 'се', 'махна'), ('искам', 'да', 'се', 'махна', 'от'), ('да', 'се', 'махна', 'от', 'българия”'), ('се', 'махна', 'от', 'българия”', 'стои'), ('махна', 'от', 'българия”', 'стои', 'осъзнат'), ('от', 'българия”', 'стои', 'осъзнат', 'избор'), ('българия”', 'стои', 'осъзнат', 'избор', 'на'), ('стои', 'осъзнат', 'избор', 'на', 'двеста'), ('осъзнат', 'избор', 'на', 'двеста', 'хиляди'), ('избор', 'на', 'двеста', 'хиляди', 'българи'), ('на', 'двеста', 'хиляди', 'българи', 'които'), ('двеста', 'хиляди', 'българи', 'които', 'са'), ('хиляди', 'българи', 'които', 'са', 'загубили'), ('българи', 'които', 'са', 'загубили', 'вяра'), ('които', 'са', 'загубили', 'вяра', 'във'), ('са', 'заг

### Word unigrams

In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [7]:
tokenizer = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n“„”–', num_words=10_000, oov_token=1)
tokenizer.fit_on_texts(X_train)
X_train = tokenizer.texts_to_sequences(X_train)

In [22]:
max([max(X_train[i]) for i in range(len(X_train))])

9999

In [21]:
# Remove texts longer than 50 words
# Max text length before this step is 2000+ words
y_train = y_train[[len(x)<=50 for x in X_train]]
X_train = [X for X in X_train if len(X)<=50]

In [39]:
print(len(X_train))
print(len(y_train))

223631
223631


In [23]:
X_train = pad_sequences(X_train)

In [48]:
# from sklearn.preprocessing import OneHotEncoder
# enc = OneHotEncoder().fit(X_train)

In [53]:
# print(enc.transform(X_train)[0])

  (0, 0)	1.0
  (0, 231)	1.0
  (0, 813)	1.0
  (0, 1647)	1.0
  (0, 2701)	1.0
  (0, 4064)	1.0
  (0, 5663)	1.0
  (0, 7512)	1.0
  (0, 9557)	1.0
  (0, 11844)	1.0
  (0, 14399)	1.0
  (0, 17140)	1.0
  (0, 20192)	1.0
  (0, 23488)	1.0
  (0, 27077)	1.0
  (0, 30979)	1.0
  (0, 35119)	1.0
  (0, 39541)	1.0
  (0, 44361)	1.0
  (0, 49417)	1.0
  (0, 54902)	1.0
  (0, 60729)	1.0
  (0, 66984)	1.0
  (0, 73587)	1.0
  (0, 80604)	1.0
  (0, 87952)	1.0
  (0, 95745)	1.0
  (0, 108884)	1.0
  (0, 119551)	1.0
  (0, 127192)	1.0
  (0, 130271)	1.0
  (0, 139520)	1.0
  (0, 148981)	1.0
  (0, 159437)	1.0
  (0, 175665)	1.0
  (0, 177899)	1.0
  (0, 195672)	1.0
  (0, 197751)	1.0
  (0, 207482)	1.0
  (0, 217895)	1.0
  (0, 227034)	1.0
  (0, 237835)	1.0
  (0, 246734)	1.0
  (0, 256596)	1.0
  (0, 267097)	1.0
  (0, 277062)	1.0
  (0, 286092)	1.0
  (0, 297793)	1.0
  (0, 311025)	1.0
  (0, 315371)	1.0


In [46]:
len(tokenizer.word_index)

627562

In [47]:
tokenizer.num_words

10000

In [17]:
tokenizer.word_index

{1: 1,
 'de': 2,
 'a': 3,
 'que': 4,
 'la': 5,
 'je': 6,
 'se': 7,
 'на': 8,
 'el': 9,
 'na': 10,
 'i': 11,
 'da': 12,
 'u': 13,
 'en': 14,
 'o': 15,
 'y': 16,
 'и': 17,
 'do': 18,
 'para': 19,
 'v': 20,
 'los': 21,
 'e': 22,
 'za': 23,
 'su': 24,
 'yang': 25,
 'за': 26,
 'del': 27,
 'sa': 28,
 'por': 29,
 'dan': 30,
 'no': 31,
 'да': 32,
 'un': 33,
 'di': 34,
 'в': 35,
 'las': 36,
 'се': 37,
 'во': 38,
 'con': 39,
 's': 40,
 'una': 41,
 'em': 42,
 'od': 43,
 'to': 44,
 'com': 45,
 'al': 46,
 'como': 47,
 'itu': 48,
 'е': 49,
 'os': 50,
 'es': 51,
 'že': 52,
 'от': 53,
 'um': 54,
 'од': 55,
 'si': 56,
 'koji': 57,
 'dos': 58,
 'dengan': 59,
 'ini': 60,
 'untuk': 61,
 'z': 62,
 'će': 63,
 'ha': 64,
 'uma': 65,
 'bi': 66,
 'dalam': 67,
 'as': 68,
 'ne': 69,
 'não': 70,
 'ng': 71,
 'не': 72,
 'po': 73,
 'pada': 74,
 'é': 75,
 'lo': 76,
 '1': 77,
 'по': 78,
 'más': 79,
 'tidak': 80,
 'со': 81,
 'с': 82,
 'ang': 83,
 'što': 84,
 'dari': 85,
 'iz': 86,
 'akan': 87,
 'kako': 88,
 'este': 89,


In [45]:
len([x for x in tokenizer.word_counts.items() if x[1] > 10])

69922

In [24]:
sorted(tokenizer.word_counts.items(), key=lambda w: w[1], reverse=False)[:150]

[('махна', 1),
 ('осъзнат', 1),
 ('потръгнаха', 1),
 ('държащи', 1),
 ('непрекъснатия', 1),
 ('явен', 1),
 ('дините', 1),
 ('антигона', 1),
 ('монпелие', 1),
 ('скъпият', 1),
 ('довежда', 1),
 ('геополитическа', 1),
 ('димене', 1),
 ('разнасят', 1),
 ('колоездачите', 1),
 ('чаба', 1),
 ('лехел', 1),
 ('тенисистката', 1),
 ('крина', 1),
 ('тугуи', 1),
 ('кустура', 1),
 ('вмъкна', 1),
 ('въдях', 1),
 ('колелцата', 1),
 ('увисват', 1),
 ('релефа', 1),
 ('флоридис', 1),
 ('нанасяйки', 1),
 ('филиалът', 1),
 ('маккан', 1),
 ('спем', 1),
 ('къмюникейшън', 1),
 ('котки', 1),
 ('неразположение', 1),
 ('мъркащия', 1),
 ('позна', 1),
 ('съселянин', 1),
 ('стопанисване', 1),
 ('начислявана', 1),
 ('реактивна', 1),
 ('димчо', 1),
 ('обособят', 1),
 ('чеширския', 1),
 ('второстепенни', 1),
 ('разпоредители', 1),
 ('пепеляшка', 1),
 ('тракийската', 1),
 ('духтев', 1),
 ('висшист', 1),
 ('двоични', 1),
 ('изважда', 1),
 ('касетите', 1),
 ('грамофонните', 1),
 ('жестове', 1),
 ('подкрепяща', 1),
 ('не

In [52]:
X_train.shape

(223631, 50)

In [19]:
print(X_train[0])

[     0      0      0      0      0      0      0      0      0      0
      0      0      0      0   5237   7750   6261  19121     31     36
 293951     52    947  12363 293952   7625      7 133393   8101  15205
    276    156 160346  30342    709  19122      7  75764    955     31
  11214  10581     34    714    828     36  69923   1952   5474    160]


In [35]:
from tensorflow.keras.utils import Sequence

In [48]:
class DataGenerator(Sequence):
    def __init__(self, input_sequences, labels, batch_size=32, shuffle=True):
        self.input_sequences = input_sequences
        self.labels = labels
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.on_epoch_end()

    # Number of batches per epoch
    def __len__(self):
        return int(np.floor(len(self.input_sequences) / self.batch_size))

    # Generate one batch
    def __getitem__(self, index):
        indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]
        X = to_categorical([self.input_sequences[index] for index in indexes], num_classes=tokenizer.num_words)
        # y = np.asarray([to_categorical(self.decoder_output[index], num_classes=self.n_classes) for index in indexes])
        y = np.asarray([self.labels[index] for index in indexes])
        return X, y

    # Update indexes for next epoch
    def on_epoch_end(self):
        self.indexes = np.arange(len(self.input_sequences))
        if self.shuffle:
            np.random.shuffle(self.indexes)

## Model

In [25]:
from tensorflow.keras import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, InputLayer, GRU, Dropout, Dense

In [41]:
NUM_EPOCHS = 50
HIDDEN_LAYER_SIZE = 768
DROPOUT_RATE = 0.45
VALIDATION_SPLIT = 0.1
BATCH_SIZE = 32

In [27]:
MAX_SENTENCE_LENGTH = X_train.shape[1]
NUM_CLASSES = y_train.shape[1]

In [28]:
print(NUM_CLASSES)

14


In [29]:
print(MAX_SENTENCE_LENGTH)
print(len(tokenizer.word_index))

50
627563


In [30]:
print(tokenizer.num_words)

10000


In [ ]:
# model_inputs = Input(shape=(max_source_len,))
# x = GRU(100)(model_inputs)
# model_output = Dense(n_decoder_tokens, activation='softmax')(x)

# model = model_output(model)

In [31]:
model = Sequential([
    InputLayer(input_shape=(MAX_SENTENCE_LENGTH,tokenizer.num_words)), #,len(tokenizer.word_index)+1)),
    GRU(HIDDEN_LAYER_SIZE),
    Dropout(rate = DROPOUT_RATE),
    Dense(NUM_CLASSES, activation='softmax')
])

2022-05-26 10:49:52.954552: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-26 10:49:52.954672: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-26 10:49:52.954758: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (clockwork): /proc/driver/nvidia/version does not exist
2022-05-26 10:49:53.022244: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 92160000 exceeds 10% of free system memory.
2022-05-26 10:49:53.188081: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 92160000 exceeds 10% of free system memory.
2022-05-26 10:49:53.258286: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 92160000 exceeds 10% of free system memory.


In [32]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [33]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru (GRU)                    (None, 768)               24814080  
_________________________________________________________________
dropout (Dropout)            (None, 768)               0         
_________________________________________________________________
dense (Dense)                (None, 14)                10766     
Total params: 24,824,846
Trainable params: 24,824,846
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# history = model.fit(
#     X_train, y_train
#     validation_split=VALIDATION_SPLIT,
#     epochs=NUM_EPOCHS,
#     batch_size=BATCH_SIZE
#     # callbacks=[checkpoint_callback]
# )

In [49]:
train_generator = DataGenerator(X_train, y_train, batch_size=BATCH_SIZE)
# validation_generator = DataGenerator()

In [50]:
history = model.fit(
    train_generator,
#     validation_data=validation_generator,
    epochs=NUM_EPOCHS,
    batch_size=BATCH_SIZE
    # callbacks=[checkpoint_callback]
)

2022-05-26 11:02:08.290341: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 64000000 exceeds 10% of free system memory.
2022-05-26 11:02:08.541041: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-05-26 11:02:08.553318: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2793590000 Hz


Epoch 1/50


2022-05-26 11:02:09.515478: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 92160000 exceeds 10% of free system memory.


  17/6539 [..............................] - ETA: 11:58:07 - loss: 2.7055 - accuracy: 0.1048

KeyboardInterrupt: 

## Ensemble

In [ ]:
from sklearn.linear_model import LinearRegression