# Language Identification

- https://cs229.stanford.edu/proj2015/324_report.pdf
- https://sites.google.com/view/vardial2021/home
- http://ttg.uni-saarland.de/resources/DSLCC/
- https://mzampieri.com/publications.html
- https://mzampieri.com/papers/dsl2016.pdf

## Make workspace

In [ ]:
# Make directories if they don't exist
!mkdir -p datasets
!mkdir -p datasets/DSLCC-v2.0
# !mkdir -p datasets/DSLCC-v2.1
!mkdir -p models

## Imports

In [ ]:
import os
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

## Download datasets

In [ ]:
# DSLCC v2.0
if not os.path.exists('datasets/DSLCC-v2.0/train.txt'):
    !cd datasets/DSLCC-v2.0 && curl -o train.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.0/train-dev/train.txt
if not os.path.exists('datasets/DSLCC-v2.0/devel.txt'):
    !cd datasets/DSLCC-v2.0 && curl -o devel.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.0/train-dev/devel.txt
if not os.path.exists('datasets/DSLCC-v2.0/test.txt'):
    !cd datasets/DSLCC-v2.0 && curl -o test.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.0/test/test.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 61.0M  100 61.0M    0     0  41.6M      0  0:00:01  0:00:01 --:--:-- 41.6M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6939k  100 6939k    0     0  16.1M      0 --:--:-- --:--:-- --:--:-- 16.1M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3401k  100 3401k    0     0  9637k      0 --:--:-- --:--:-- --:--:-- 9609k


In [ ]:
# # DSLCC v2.1
# if not os.path.exists('datasets/DSLCC-v2.1/train.txt'):
#     !cd datasets/DSLCC-v2.1 && curl -o train.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.1/train.txt
# if not os.path.exists('datasets/DSLCC-v2.1/devel.txt'):
#     !cd datasets/DSLCC-v2.1 && curl -o devel.txt https://raw.githubusercontent.com/alvations/bayesmax/master/bayesmax/data/DSLCC-v2.1/devel.txt

## Data

### Languages

<table>
    <tr>
        <th>Group Name</th>
        <th>Language Name</th>
        <th>Language Code</th>
    </tr>
    <tr>
        <td rowspan=2>South Eastern Slavic</td>
        <td>Bulgarian</td>
        <td>bg</td>
    </tr>
    <tr>
        <td>Macedonian</td>
        <td>mk</td>
    </tr>
    <tr>
        <td rowspan=3>South Western Slavic</td>
        <td>Bosnian</td>
        <td>bs</td>
    </tr>
    <tr>
        <td>Croatian</td>
        <td>hr</td>
    </tr>
    <tr>
        <td>Serbian</td>
        <td>sr</td>
    </tr>
    <tr>
        <td rowspan=2>West-Slavic</td>
        <td>Czech</td>
        <td>cz</td>
    </tr>
    <tr>
        <td>Slovak</td>
        <td>sk</td>
    </tr>
    <tr>
        <td rowspan=2>Ibero-Romance (Spanish)</td>
        <td>Peninsular Spanish</td>
        <td>es-ES</td>
    </tr>
    <tr>
        <td>Argentinian Spanish</td>
        <td>es-AR</td>
    </tr>
    <tr>
        <td rowspan=2>Ibero-Romance (Portugese)</td>
        <td>Brazilian Portugese</td>
        <td>pt-BR</td>
    </tr>
    <tr>
        <td>European Portugese</td>
        <td>pt-PT</td>
    </tr>
    <tr>
        <td rowspan=2>Astronesian</td>
        <td>Indonesian</td>
        <td>id</td>
    </tr>
    <tr>
        <td>Malay</td>
        <td>my</td>
    </tr>
</table>

In [ ]:
train = pd.read_csv('datasets/DSLCC-v2.0/train.txt', sep='\t', names=['sentence', 'language'])
validation = pd.read_csv('datasets/DSLCC-v2.0/devel.txt', sep='\t', names=['sentence', 'language'])
test = pd.read_csv('datasets/DSLCC-v2.0/test.txt', sep='\t', names=['sentence', 'language'])

In [ ]:
print(f'Training set size:   {len(train)}')
print(f'Validation set size: {len(validation)}')
print(f'Test set size:       {len(test)}')

Training set size:   236135
Validation set size: 26335
Test set size:       13229


In [ ]:
# Print number of instances per label
print(train['language'].value_counts())

es-ES    17990
es-AR    17808
sr       17442
pt-PT    17284
id       17195
mk       17154
bg       17151
xx       16920
bs       16858
hr       16792
pt-BR    16483
cz       16454
sk       16224
my       14380
Name: language, dtype: int64


In [ ]:
print(train.head())

                                            sentence language
0  Зад думите “просто искам да се махна от Българ...       bg
1  Сега нещата там леко потръгнаха с усилията на ...       bg
2  Хърватският филм "Пътят на дините" на режисьор...       bg
3  Министърът на правосъдието на РС Джерард Селма...       bg
4  В крайна сметка войната между Севера и Юга дов...       bg


## Preprocessing

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
X_train_original = train['sentence']
y_train_original = train['language']
X_validation_original = validation['sentence']
y_validation_original = validation['language']

In [ ]:
X_train = train['sentence']
y_train = train['language']

In [ ]:
print(X_train.head())
print(y_train.head())

0    Зад думите “просто искам да се махна от Българ...
1    Сега нещата там леко потръгнаха с усилията на ...
2    Хърватският филм "Пътят на дините" на режисьор...
3    Министърът на правосъдието на РС Джерард Селма...
4    В крайна сметка войната между Севера и Юга дов...
Name: sentence, dtype: object
0    bg
1    bg
2    bg
3    bg
4    bg
Name: language, dtype: object


In [ ]:
y_train = pd.get_dummies(y_train).to_numpy()

In [ ]:
print(y_train)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


### Character n-grams

In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from nltk.util import ngrams
from itertools import chain
from tqdm import tqdm
tqdm.pandas()

In [ ]:
def sentence_to_char_ngram(sentence, n):
    s = ''.join([c if c not in '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n“„”–' else ' ' for c in sentence])
    tokens = text_to_word_sequence(s)
    ngrams_ = [[''.join(ng) for ng in list(ngrams(token, n))] for token in tokens if len(token) >= n]
    return ' '.join(chain.from_iterable(ngrams_))

In [ ]:
def get_char_ngram_train_set(X, n):
  X_ngram_train = X.copy()
  print(f'{n} - gramming')
  return X_ngram_train.progress_apply(lambda sentence: sentence_to_char_ngram(sentence, n))
  

In [ ]:
X_2gram_train = get_char_ngram_train_set(2)
X_3gram_train = get_char_ngram_train_set(3)
X_4gram_train = get_char_ngram_train_set(4)
X_5gram_train = get_char_ngram_train_set(5)

2 - gramming


100%|██████████| 236135/236135 [00:40<00:00, 5809.16it/s]


3 - gramming


100%|██████████| 236135/236135 [00:36<00:00, 6421.03it/s]


4 - gramming


100%|██████████| 236135/236135 [00:33<00:00, 7032.40it/s]


5 - gramming


100%|██████████| 236135/236135 [00:30<00:00, 7766.91it/s]


In [ ]:
print(X_2gram_train.head())
print(X_5gram_train.head())

0    за ад ду ум ми ит те пр ро ос ст то ис ск ка а...
1    се ег га не ещ ща ат та та ам ле ек ко по от т...
2    хъ ър рв ва ат тс ск ки ия ят фи ил лм пъ ът т...
3    ми ин ни ис ст тъ ър ръ ът на пр ра ав во ос с...
4    кр ра ай йн на см ме ет тк ка во ой йн на ат т...
Name: sentence, dtype: object
0    думит умите прост росто искам махна бълга ълга...
1    нещат ещата потръ отръг тръгн ръгна ъгнах гнах...
2    хърва ърват рватс ватск атски тския ският пътя...
3    минис инист нистъ истър стъръ търът право раво...
4    крайн райна сметк метка война ойнат йната межд...
Name: sentence, dtype: object


In [ ]:
X_train_char4gram = [sentence_to_char_ngram(s, 4) for s in train['sentence']]

In [ ]:
print(X_train_char4gram[6])

['пред', 'реди', 'дире', 'ирек', 'рект', 'екто', 'ктор', 'торъ', 'орът', 'исто', 'стор', 'тори', 'орич', 'риче', 'ичес', 'ческ', 'ески', 'ския', 'музе', 'узей', 'полс', 'олск', 'лски', 'тръм', 'ръмб', 'ъмбе', 'мбеш', 'хрис', 'рист', 'исто', 'хари', 'арит', 'рито', 'итон', 'тоно', 'онов', 'ходи', 'одил', 'дили', 'видя', 'идят', 'мощи', 'ощит', 'щите', 'църк', 'ъркв', 'рква', 'кват', 'вата', 'созо', 'озоп', 'зопо', 'опол', 'коит', 'оито', 'вече', 'разн', 'азна', 'знас', 'нася', 'асят', 'леге', 'еген', 'генд', 'енди', 'имал', 'мали', 'чудо', 'удод', 'доде', 'одей', 'дейн', 'ейна', 'сила']


### Word unigrams

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n“„”–', num_words=10_000, oov_token=1)
tokenizer.fit_on_texts(X_train)
X_train = tokenizer.texts_to_sequences(X_train)

In [ ]:
max([max(X_train[i]) for i in range(len(X_train))])

9999

In [ ]:
# Remove texts longer than 50 words
# Max text length before this step is 2000+ words
y_train = y_train[[len(x)<=50 for x in X_train]]
X_train = [X for X in X_train if len(X)<=50]

In [ ]:
print(len(X_train))
print(len(y_train))

209268
209268


In [ ]:
X_train = pad_sequences(X_train)

In [ ]:
len(tokenizer.word_index)

In [ ]:
tokenizer.word_index

In [ ]:
len([x for x in tokenizer.word_counts.items() if x[1] > 10])

In [ ]:
sorted(tokenizer.word_counts.items(), key=lambda w: w[1], reverse=False)[:150]

In [ ]:
X_train.shape

In [ ]:
print(X_train[0])

In [ ]:
from tensorflow.keras.utils import Sequence

In [ ]:
class DataGenerator(Sequence):
    def __init__(self, input_sequences, labels, num_classes, batch_size=32, shuffle=True):
        self.input_sequences = input_sequences
        self.labels = labels
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.on_epoch_end()
        self.num_classes = num_classes

    # Number of batches per epoch
    def __len__(self):
        return int(np.floor(len(self.input_sequences) / self.batch_size))

    # Generate one batch
    def __getitem__(self, index):
        indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]
        X = to_categorical([self.input_sequences[index] for index in indexes], num_classes=self.num_classes)
        # y = np.asarray([to_categorical(self.decoder_output[index], num_classes=self.n_classes) for index in indexes])
        y = np.asarray([self.labels[index] for index in indexes])
        return X, y

    # Update indexes for next epoch
    def on_epoch_end(self):
        self.indexes = np.arange(len(self.input_sequences))
        if self.shuffle:
            np.random.shuffle(self.indexes)

## Model

In [ ]:
from tensorflow.keras import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, GRU, Dropout, Dense

In [ ]:
OPTIMIZER = 'adam'
EPOCHS = 20
BATCH_SIZE = 32
HIDDEN_LAYER_SIZE = 768
DROPOUT_RATE = 0.45

In [ ]:
# MAX_SENTENCE_LENGTH = X_train.shape[1]
NUM_CLASSES = y_train.shape[1]

In [ ]:
# print(MAX_SENTENCE_LENGTH)
# print(NUM_CLASSES)

14


In [ ]:
# model = Sequential([
#     InputLayer(input_shape=(MAX_SENTENCE_LENGTH,tokenizer.num_words)), #,len(tokenizer.word_index)+1)),
#     GRU(HIDDEN_LAYER_SIZE),
#     Dropout(rate = DROPOUT_RATE),
#     Dense(NUM_CLASSES, activation='softmax')
# ])

2022-05-31 15:33:31.432574: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-31 15:33:31.432666: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-31 15:33:31.432783: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (clockwork): /proc/driver/nvidia/version does not exist
2022-05-31 15:33:31.519029: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 92160000 exceeds 10% of free system memory.
2022-05-31 15:33:31.709392: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 92160000 exceeds 10% of free system memory.
2022-05-31 15:33:31.769857: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 92160000 exceeds 10% of free system memory.


In [ ]:
# model.compile(optimizer=OPTIMIZER, loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
# model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru (GRU)                    (None, 768)               24814080  
_________________________________________________________________
dropout (Dropout)            (None, 768)               0         
_________________________________________________________________
dense (Dense)                (None, 14)                10766     
Total params: 24,824,846
Trainable params: 24,824,846
Non-trainable params: 0
_________________________________________________________________


In [ ]:
def plot_history(history):
    plt.plot(history.epoch, history.history['accuracy'])
    plt.plot(history.epoch, history.history['val_accuracy'])
    plt.legend(['Training accuracy', 'Validation accuracy'])

In [ ]:
# model_name = f'models/model_{EPOCHS}_{BATCH_SIZE}_{HIDDEN_LAYER_SIZE}_{int(100*DROPOUT_RATE)}_{time.strftime("%Y%m%d_%H%M%S")}'

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath='models/checkpoint',
    save_weights_only=True,
    monitor='val_accuracy',
    mode='max',
    verbose=1
)

# # train_generator = DataGenerator(X_train, y_train, batch_size=BATCH_SIZE)
# # validation_generator = DataGenerator()

# history = model.fit(
#     train_generator,
# #     validation_data=validation_generator,
#     epochs=EPOCHS,
#     batch_size=BATCH_SIZE,
#     callbacks=[checkpoint_callback]
# )

# # Save trained model, compilation and training data and history plot
# model.save(model_name)
# with open(f'{model_name}/training.txt', 'w') as f:
#     f.write(f'OPTIMIZER:    \t {OPTIMIZER}\n')
#     f.write(f'EPOCHS:       \t {EPOCHS}\n')
#     f.write(f'BATCH:        \t {BATCH_SIZE}\n')
#     f.write(f'HIDDEN LAYER: \t {HIDDEN_LAYER_SIZE}\n')
#     f.write(f'DROUPOUT:     \t {DROPOUT_RATE}\n')
#     model.summary(print_fn = lambda x: f.write(x + '\n'))
# plot_history(history)
# plt.savefig(f'{model_name}/history.png')




In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
import json

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath='models/checkpoint',
    save_weights_only=True,
    monitor='val_accuracy',
    mode='max',
    verbose=1
)

def get_model(input_shape, hidden_layer_size=HIDDEN_LAYER_SIZE, recurrent_dropout=DROPOUT_RATE):
  model = Sequential([
    InputLayer(input_shape=input_shape), #,len(tokenizer.word_index)+1)),
    GRU(HIDDEN_LAYER_SIZE, recurrent_dropout=DROPOUT_RATE),
    # Dropout(rate = DROPOUT_RATE),
    Dense(NUM_CLASSES, activation='softmax')
  ])
  model.compile(optimizer=OPTIMIZER, loss='categorical_crossentropy', metrics=['accuracy'])
  return model

def grid_search_model(devel_X_processor=lambda x: x):
  y_dummies = pd.get_dummies(y_validation_original).to_numpy()
  X = devel_X_processor(X_validation_original.copy())

  devel_train_X, devel_test_X, devel_train_Y, devel_test_Y = train_test_split(X, \
                                                                              y_dummies, \
                                                                              train_size=0.75, stratify=y_dummies)
  
  tokenizer = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n“„”–', num_words=10_000, oov_token=1)
  tokenizer.fit_on_texts(devel_train_X)
  devel_train_X = tokenizer.texts_to_sequences(devel_train_X)
  devel_test_X = tokenizer.texts_to_sequences(devel_test_X)

  devel_train_Y = devel_train_Y[[len(x)<=50 for x in devel_train_X]]
  devel_train_X = [x for x in devel_train_X if len(x)<=50]
  devel_train_X = pad_sequences(devel_train_X)

  devel_test_Y = devel_test_Y[[len(x)<=50 for x in devel_test_X]]
  devel_test_X = [x for x in devel_test_X if len(x)<=50]
  devel_test_X = pad_sequences(devel_test_X)

  results = np.zeros((3, 5))

  for i, hidden_layer_size in enumerate([768, 1024, 1280]):
    for j, dropout_rate in enumerate([0.2, 0.25, 0.35, 0.4, 0.45]):
      if i == 0 and j == 0:
        continue
      print(f'Training params: hidden layer size={hidden_layer_size}, dropout rate={dropout_rate}')
      devel_train_generator = DataGenerator(devel_train_X, devel_train_Y, num_classes=tokenizer.num_words, batch_size=BATCH_SIZE)
      devel_test_generator = DataGenerator(devel_test_X, devel_test_Y, num_classes=tokenizer.num_words, batch_size=BATCH_SIZE)
      model = get_model((devel_train_X.shape[1], tokenizer.num_words), hidden_layer_size, dropout_rate)
      history = model.fit(
        devel_train_generator,
        validation_data=devel_test_generator,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        callbacks=[checkpoint_callback]
      )
      
      print(f'Accuracy: {i}, {j}, ----- {history.history["accuracy"]}')
      print(f'Val accuracy: {i}, {j}, ----- {history.history["val_accuracy"]}')
  

  gsdf = pd.DataFrame(results, index=[768, 1024, 1280], columns=[0.2, 0.25, 0.35, 0.4, 0.45])
  gsdf.to_csv('grid_search.csv')
  print(gsdf)
  


def fit_model(X, Y, name):
  train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.9, stratify=Y)
  train_generator = DataGenerator(train_X, train_Y, batch_size=BATCH_SIZE)
  val_generator = DataGenerator(val_X, val_Y, batch_size=BATCH_SIZE)

  model_name = f'models/model_{name}_{EPOCHS}_{BATCH_SIZE}_{HIDDEN_LAYER_SIZE}_{int(100*DROPOUT_RATE)}_{time.strftime("%Y%m%d_%H%M%S")}'

  tokenizer = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n“„”–', num_words=10_000, oov_token=1)
  tokenizer.fit_on_texts(train_X)
  train_X = tokenizer.texts_to_sequences(train_X)

  MAX_SENTENCE_LENGTH = train_X.shape[1]
  model = get_model((MAX_SENTENCE_LENGTH, tokenizer.num_words))

  history = model.fit(
      train_generator,
      validation_data=val_generator,
      epochs=EPOCHS,
      batch_size=BATCH_SIZE,
      callbacks=[checkpoint_callback]
  )

  model.save(model_name)
  with open(f'{model_name}/training.txt', 'w') as f:
      f.write(f'OPTIMIZER:    \t {OPTIMIZER}\n')
      f.write(f'EPOCHS:       \t {EPOCHS}\n')
      f.write(f'BATCH:        \t {BATCH_SIZE}\n')
      f.write(f'HIDDEN LAYER: \t {HIDDEN_LAYER_SIZE}\n')
      f.write(f'DROUPOUT:     \t {DROPOUT_RATE}\n')
      model.summary(print_fn = lambda x: f.write(x + '\n'))

  plot_history(history)
  plt.savefig(f'{model_name}/history.png')




  

In [ ]:
pd.DataFrame([[1,2], [3, 4]], index=['nesto', 'ovde'], columns=['druga', 'stvar'])

,druga,stvar
nesto,1,2
ovde,3,4


In [ ]:
print(f'asdasdas {[1, 2, 3, 4, 5]}')

asdasdas [1, 2, 3, 4, 5]


In [ ]:
grid_search_model()

Training params: hidden layer size=768, dropout rate=0.25
Epoch 1/20
549/549 [==============================] - ETA: 0s - loss: 1.0907 - accuracy: 0.5339
Epoch 1: saving model to models/checkpoint
549/549 [==============================] - 261s 472ms/step - loss: 1.0907 - accuracy: 0.5339 - val_loss: 0.5491 - val_accuracy: 0.7220
Epoch 2/20
549/549 [==============================] - ETA: 0s - loss: 0.4327 - accuracy: 0.8001
Epoch 2: saving model to models/checkpoint
549/549 [==============================] - 257s 468ms/step - loss: 0.4327 - accuracy: 0.8001 - val_loss: 0.4124 - val_accuracy: 0.7940
Epoch 3/20
549/549 [==============================] - ETA: 0s - loss: 0.3070 - accuracy: 0.8693
Epoch 3: saving model to models/checkpoint
549/549 [==============================] - 257s 468ms/step - loss: 0.3070 - accuracy: 0.8693 - val_loss: 0.4092 - val_accuracy: 0.8163
Epoch 4/20
549/549 [==============================] - ETA: 0s - loss: 0.1915 - accuracy: 0.9239
Epoch 4: saving model to

In [ ]:
# 0, 0 ---- val accuracy: 0.8394573926925659

## Ensemble

In [ ]:
from sklearn.linear_model import LinearRegression